#!/usr/bin/env python3

# Hi! This is a draft script GENERATED BY AI
# PLEASE do not run this as is.
# This is just a draft to demonstrate a possibility.
# Heavy edits are required before making this a published reality, never mind run for tests.
# Edit.
# This.
# Script..

import evdev
import uinput
import time
import sys

# -----------------------------
# CONFIGURATION
# -----------------------------
REAL_DEVICE = "/dev/input/event12"   # change to your device
MAP = {
    "x": evdev.ecodes.ABS_X,
    "y": evdev.ecodes.ABS_Y,
    "pressure": evdev.ecodes.ABS_Z,
    "tilt_x": evdev.ecodes.ABS_RX,
    "tilt_y": evdev.ecodes.ABS_RY,
}
# Tablet ranges
TABLET_MAX_X = 32767
TABLET_MAX_Y = 32767
PRESSURE_MAX = 1023
TILT_MAX = 90
# -----------------------------

def scale(value, src_min, src_max, dst_min, dst_max):
    if src_max == src_min:
        return dst_min
    return int((value - src_min) / (src_max - src_min) * (dst_max - dst_min) + dst_min)

def main():
    dev = evdev.InputDevice(REAL_DEVICE)
    caps = dev.capabilities(absinfo=True)

    # Extract source ranges
    src = {}
    for name, code in MAP.items():
        if code in caps.get(evdev.ecodes.EV_ABS, {}):
            info = caps[evdev.ecodes.EV_ABS][code]
            src[name] = (info.min, info.max)

    # Create virtual tablet
    events = [
        uinput.BTN_TOOL_PEN,
        uinput.BTN_TOUCH,
        uinput.ABS_X + (0, TABLET_MAX_X, 0, 0),
        uinput.ABS_Y + (0, TABLET_MAX_Y, 0, 0),
        uinput.ABS_PRESSURE + (0, PRESSURE_MAX, 0, 0),
        uinput.ABS_TILT_X + (-TILT_MAX, TILT_MAX, 0, 0),
        uinput.ABS_TILT_Y + (-TILT_MAX, TILT_MAX, 0, 0),
    ]

    ui = uinput.Device(events, name="Virtual Pen Tablet")

    ui.emit(uinput.BTN_TOOL_PEN, 1, syn=False)

    for event in dev.read_loop():
        if event.type == evdev.ecodes.EV_ABS:
            for name, code in MAP.items():
                if event.code == code:
                    vmin, vmax = src[name]
                    if name == "x":
                        ui.emit(uinput.ABS_X,
                                scale(event.value, vmin, vmax, 0, TABLET_MAX_X),
                                syn=False)
                    elif name == "y":
                        ui.emit(uinput.ABS_Y,
                                scale(event.value, vmin, vmax, 0, TABLET_MAX_Y),
                                syn=False)
                    elif name == "pressure":
                        p = scale(event.value, vmin, vmax, 0, PRESSURE_MAX)
                        ui.emit(uinput.A
